module.exports = {
    BASE_URL: 'http://192.168.1.102:3333/api',
    NEWS_PAGE: '/news/all-paginated',
    NEWS_ALL: '/news',
    NEWS_SLUG: '/news/slug/find',
    NEWS_COMMENT: '/news-comment/store',
    GALLERY_ALL: '/gallery/all-paginated',
    BOOKS: '/book',
    BOOKS_ALL: '/book/all-paginated',
    BOOK_Find: '/book',
    BOOK_FILE: '/book/get-file',
    VIDEO_ALL: '/video/all-paginated',
    AUDIO_ALL: '/sound/all-paginated',
    ARTICLE_ALL: '/article/all-paginated',
    POEM_ALL: '/poem/all-paginated',
    ACTIVITY_ALL: '/activity/all-paginated',
    COMPETITIONS: '/competition',
    COMPETITION_APPLICATION: '/competition/apply-competition',
    COMPETITIONS_FINISHED_ALL: '/competition/finished/all-paginated',
    COMPETITIONS_AVAILABLE_ALL: '/competition/available/all-paginated',
    ABOUT_SOAUD: '/about/get-about',
    ABOUT_ALL: '/about',
    SLIDER_ALL: '/slider',
    SUBSCRIBE: '/subscribe/store',
    GET_DATES: '/utility/get-dates',
};
